export const disputeArbiterAbi = [
  {
    type: "constructor",
    inputs: [{ name: "_veritas", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "raiseDispute",
    inputs: [
      { name: "respondent", type: "address" },
      { name: "question", type: "string" },
      { name: "claimantEvidenceUrls", type: "string[]" },
    ],
    outputs: [{ name: "disputeId", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "submitEvidence",
    inputs: [
      { name: "disputeId", type: "uint256" },
      { name: "evidenceUrls", type: "string[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveDispute",
    inputs: [{ name: "disputeId", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claimBounty",
    inputs: [{ name: "disputeId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getDispute",
    inputs: [{ name: "disputeId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct DisputeArbiter.Dispute",
        components: [
          { name: "question", type: "string" },
          { name: "claimant", type: "address" },
          { name: "respondent", type: "address" },
          { name: "claimantEvidenceUrls", type: "string[]" },
          { name: "respondentEvidenceUrls", type: "string[]" },
          { name: "bounty", type: "uint256" },
          { name: "verdictId", type: "uint256" },
          { name: "resolved", type: "bool" },
          { name: "winner", type: "address" },
          { name: "createdAt", type: "uint256" },
          { name: "evidenceDeadline", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextDisputeId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "disputes",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "question", type: "string" },
      { name: "claimant", type: "address" },
      { name: "respondent", type: "address" },
      { name: "bounty", type: "uint256" },
      { name: "verdictId", type: "uint256" },
      { name: "resolved", type: "bool" },
      { name: "winner", type: "address" },
      { name: "createdAt", type: "uint256" },
      { name: "evidenceDeadline", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "EVIDENCE_WINDOW",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasClaimed",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resolveCallback",
    inputs: [{ name: "disputeId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "DisputeRaised",
    inputs: [
      { name: "disputeId", type: "uint256", indexed: true },
      { name: "claimant", type: "address", indexed: true },
      { name: "respondent", type: "address", indexed: true },
      { name: "question", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EvidenceSubmitted",
    inputs: [
      { name: "disputeId", type: "uint256", indexed: true },
      { name: "respondent", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "DisputeResolved",
    inputs: [
      { name: "disputeId", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BountyClaimed",
    inputs: [
      { name: "disputeId", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "error",
    name: "NotRespondent",
    inputs: [],
  },
  {
    type: "error",
    name: "EvidenceWindowClosed",
    inputs: [],
  },
  {
    type: "error",
    name: "AlreadyResolved",
    inputs: [],
  },
  {
    type: "error",
    name: "NotWinner",
    inputs: [],
  },
  {
    type: "error",
    name: "NoBounty",
    inputs: [],
  },
  {
    type: "error",
    name: "AlreadyClaimed",
    inputs: [],
  },
  {
    type: "error",
    name: "DisputeNotResolved",
    inputs: [],
  },
] as const;
