export const insuranceVaultAbi = [
  {
    type: "constructor",
    inputs: [{ name: "_veritas", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "createPolicy",
    inputs: [
      { name: "question", type: "string" },
      { name: "evidenceUrls", type: "string[]" },
      { name: "premium", type: "uint256" },
      { name: "payoutAmount", type: "uint256" },
      { name: "maxParticipants", type: "uint256" },
    ],
    outputs: [{ name: "policyId", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getPolicy",
    inputs: [{ name: "policyId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct InsuranceVault.Policy",
        components: [
          { name: "question", type: "string" },
          { name: "evidenceUrls", type: "string[]" },
          { name: "premium", type: "uint256" },
          { name: "payoutAmount", type: "uint256" },
          { name: "maxParticipants", type: "uint256" },
          { name: "participantCount", type: "uint256" },
          { name: "verdictId", type: "uint256" },
          { name: "resolved", type: "bool" },
          { name: "outcome", type: "bool" },
          { name: "createdAt", type: "uint256" },
          { name: "creator", type: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "joinPolicy",
    inputs: [{ name: "policyId", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claimPayout",
    inputs: [{ name: "policyId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolvePolicy",
    inputs: [{ name: "policyId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "nextPolicyId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "policies",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "question", type: "string" },
      { name: "premium", type: "uint256" },
      { name: "payoutAmount", type: "uint256" },
      { name: "maxParticipants", type: "uint256" },
      { name: "participantCount", type: "uint256" },
      { name: "verdictId", type: "uint256" },
      { name: "resolved", type: "bool" },
      { name: "outcome", type: "bool" },
      { name: "createdAt", type: "uint256" },
      { name: "creator", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isParticipant",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasClaimed",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getParticipants",
    inputs: [{ name: "policyId", type: "uint256" }],
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PolicyCreated",
    inputs: [
      { name: "policyId", type: "uint256", indexed: true },
      { name: "question", type: "string", indexed: false },
      { name: "premium", type: "uint256", indexed: false },
      { name: "payoutAmount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PolicyJoined",
    inputs: [
      { name: "policyId", type: "uint256", indexed: true },
      { name: "participant", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "PolicyResolved",
    inputs: [
      { name: "policyId", type: "uint256", indexed: true },
      { name: "outcome", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PayoutClaimed",
    inputs: [
      { name: "policyId", type: "uint256", indexed: true },
      { name: "participant", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "error",
    name: "PolicyFull",
    inputs: [],
  },
  {
    type: "error",
    name: "AlreadyJoined",
    inputs: [],
  },
  {
    type: "error",
    name: "PolicyAlreadyResolved",
    inputs: [],
  },
  {
    type: "error",
    name: "NotResolved",
    inputs: [],
  },
  {
    type: "error",
    name: "NoPayout",
    inputs: [],
  },
  {
    type: "error",
    name: "AlreadyClaimed",
    inputs: [],
  },
  {
    type: "error",
    name: "NotParticipant",
    inputs: [],
  },
  {
    type: "error",
    name: "InsufficientPremium",
    inputs: [],
  },
] as const;
