export const veritasAbi = [
  {
    type: "constructor",
    inputs: [{ name: "_platform", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "getVerdict",
    inputs: [{ name: "verdictId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct Verdict",
        components: [
          { name: "requester", type: "address" },
          { name: "question", type: "string" },
          { name: "evidenceUrls", type: "string[]" },
          { name: "mode", type: "uint8" },
          { name: "payoutTarget", type: "address" },
          { name: "payoutCalldata", type: "bytes" },
          { name: "stage", type: "uint8" },
          { name: "deadline", type: "uint256" },
          { name: "evidenceCursor", type: "uint256" },
          { name: "gatheredEvidence", type: "string[]" },
          { name: "result", type: "bool" },
          { name: "confidence", type: "uint8" },
          { name: "reasoningRef", type: "bytes32" },
          { name: "lastRequestId", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requestVerdict",
    inputs: [
      { name: "question", type: "string" },
      { name: "evidenceUrls", type: "string[]" },
      { name: "mode", type: "uint8" },
      { name: "payoutTarget", type: "address" },
      { name: "payoutCalldata", type: "bytes" },
    ],
    outputs: [{ name: "verdictId", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "quoteVerdict",
    inputs: [
      { name: "mode", type: "uint8" },
      { name: "numEvidenceUrls", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poke",
    inputs: [{ name: "verdictId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestToVerdict",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "VerdictRequested",
    inputs: [
      { name: "verdictId", type: "uint256", indexed: true },
      { name: "requester", type: "address", indexed: true },
      { name: "question", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "VerdictResolved",
    inputs: [
      { name: "verdictId", type: "uint256", indexed: true },
      { name: "result", type: "bool", indexed: false },
      { name: "confidence", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "VerdictFailed",
    inputs: [
      { name: "verdictId", type: "uint256", indexed: true },
      { name: "reason", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "VerdictPoked",
    inputs: [
      { name: "verdictId", type: "uint256", indexed: true },
    ],
  },
  {
    type: "event",
    name: "CallbackFailed",
    inputs: [
      { name: "verdictId", type: "uint256", indexed: true },
      { name: "payoutTarget", type: "address", indexed: false },
    ],
  },
  {
    type: "function",
    name: "nextVerdictId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "verdictToSubscription",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "timestampToVerdictId",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "onEvent",
    inputs: [
      { name: "emitter", type: "address" },
      { name: "eventTopics", type: "bytes32[]" },
      { name: "data", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [{ name: "interfaceId", type: "bytes4" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
] as const;
